### ISSUE TITLE
Custom fact is in the wrong directory

### ISSUE THREAD

**Issue by dgrstl** [puppet-community/puppet-iis#46]
Custom facts should be in lib, not manifests/lib.

**Comment by amwilson** [comment]
Good catch... this was part of an accidental copy, I don't think it is used yet but I'll get it moved anyway

**Comment by vchepkov** [comment]
Could you release a new version of the module, please?
According to PuppetLabs support this bug has caused memory leak and eventual crash of PE 3.8 puppetserver

**Comment by nibalizer** [comment]
Thats crazy. Yes we should be able to release at any time. If @liamjbennett doesn't get around to it soon I'll cut a release for you.

**Comment by liamjbennett** [comment]
Just released in v1.4.1

**Comment by nibalizer** [comment]
\o/
