### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by nurriz** [puppet-community/puppet-iis#69]
If you, like we do, rely on getting the module from the forge, you get stuck with some really old code. Can it really be true that a version bump haven't been appropriate for 6-7 months?

**Comment by igalic** [comment]
@nurriz from what i gather, this module hasn't been [modulesync'd](https://github.com/puppet-community/modulesync) [yet](https://github.com/puppet-community/modulesync_config)

if you'd like to help us with that, i can add you as contributor.
once module-sync'd, [***anyone*** will be able to do a version-bump](https://puppet.community/docs.html#publishing)

**Comment by nibalizer** [comment]
@nurriz feel free to hop in #puppet-community on freenode and we can help you get started with the fixes igalic has pointed out need to be done.

Essentially we have to get the release pipeline set up and then releases can happen.

**Comment by nurriz** [comment]
Thanks for the input guys, I'll look into getting involved with this process. I have some reading and understanding to go, so I'll bulk up a bit on this during the weekend.
